// Scriptwriter module v2.0 — Hook-First, Viral-Optimized
// Generates YouTube Shorts scripts with attention-grabbing hooks,
// viral title formulas, and engagement-optimized descriptions with hashtags.

// Viral hook templates — first 2 seconds determine if viewer stays
const HOOK_TEMPLATES = [
  `This free AI tool is replacing {ROLE} and nobody is talking about it.`,
  `Stop doing {TASK} manually. This AI does it in 10 seconds.`,
  `I found a {PRICE} tool that does what {EXPENSIVE} charges $500 for.`,
  `{NUMBER} million people are using this AI tool and you've never heard of it.`,
  `Your {ROLE} doesn't want you to know about this tool.`,
  `I tested {NAME} for 30 days. Here's the truth.`,
  `This AI just made {TASK} completely obsolete.`,
  `Delete {COMPETITOR} right now. This is better and it's free.`,
];

// Viral title templates
const TITLE_TEMPLATES = [
  `This AI tool is REPLACING {ROLE}... 🤯`,
  `Stop using {COMPETITOR}. Use THIS instead.`,
  `{NAME} just changed EVERYTHING 🚨`,
  `FREE AI tool that does {TASK} in seconds`,
  `I can't believe this AI tool is FREE 😱`,
  `{ROLE} are PANICKING because of this tool`,
  `The AI tool nobody talks about (but should) 🤫`,
  `How to {TASK} in 10 seconds (FREE AI)`,
];

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function fillTemplate(template, vars) {
  let result = template;
  for (const [key, value] of Object.entries(vars)) {
    result = result.replace(new RegExp(`\\{${key}\\}`, 'g'), value);
  }
  return result;
}

// Tool-specific configurations for hooks and scripts
const TOOL_CONFIGS = {
  'v0.dev': {
    role: 'web developers',
    task: 'building websites',
    competitor: 'Webflow',
    expensive: 'design agencies',
    storyboard: (name, tagline, features, pricing) => [
      {
        timeRange: '00:00 - 00:05',
        visual: `Bold shaking text: "This AI builds websites in 10 SECONDS" — zoom into ${name} landing page`,
        audio: `Stop building websites manually. This AI tool generates full production websites from a single sentence.`
      },
      {
        timeRange: '00:05 - 00:18',
        visual: `Show typing a prompt into ${name}: "Build a dark SaaS dashboard with analytics". Show code generating in real-time.`,
        audio: `It's called ${name}. You just describe what you want in plain English, and it writes production-ready React code with Tailwind CSS in under ten seconds. No templates. No drag and drop. Pure AI.`
      },
      {
        timeRange: '00:18 - 00:35',
        visual: `Split screen: Left shows the live generated UI. Right shows clean code. Click "Copy Code" button. Show deploying to Vercel.`,
        audio: `Look at this output. Fully responsive components. Dark mode. Animations. And you can iterate by just chatting — say "make the sidebar collapsible" and it updates instantly. This used to take designers three days.`
      },
      {
        timeRange: '00:35 - 00:48',
        visual: `Quick montage: landing pages, dashboards, e-commerce UIs all generated by ${name}. Counter showing "10 seconds each".`,
        audio: `Freelancers are charging clients $2000 for landing pages that ${name} builds in ten seconds. Whether you're a founder, student, or developer — this changes everything.`
      },
      {
        timeRange: '00:48 - 00:60',
        visual: `Show free tier pricing. Giant animated arrow pointing down. Text: "🔗 FREE — Link in bio!"`,
        audio: `The best part? It's free to start. Link is in the description. Try it right now and comment what you built — I'll feature the best ones. Subscribe for daily AI tools.`
      }
    ]
  },
  'elevenlabs': {
    role: 'voice actors',
    task: 'voiceover recording',
    competitor: 'Fiverr voice actors',
    expensive: 'voice studios',
    storyboard: (name, tagline, features, pricing) => [
      {
        timeRange: '00:00 - 00:05',
        visual: `Waveform animation. Text flashing: "REAL VOICE or AI?" — show play button being clicked`,
        audio: `Is this voice real or AI? You literally cannot tell the difference anymore.`
      },
      {
        timeRange: '00:05 - 00:18',
        visual: `Show ${name} dashboard. Paste text into the editor. Select voice "Antoni". Click generate.`,
        audio: `This is ${name}. Paste any text — a script, an article, even a book — pick from hundreds of ultra-realistic voices, and it narrates it with perfect breathing, emotion, and pacing.`
      },
      {
        timeRange: '00:18 - 00:35',
        visual: `Show voice cloning feature. Record 30 seconds of voice. AI generates clone. Side-by-side comparison playing.`,
        audio: `But here's what's insane — you can clone your own voice. Record thirty seconds of audio and the AI recreates your voice perfectly. Twenty-nine languages. Any accent. This is replacing entire voiceover studios.`
      },
      {
        timeRange: '00:35 - 00:48',
        visual: `Show the Reader app. Upload PDF. AI reads it aloud. Show audiobook-style playback on mobile.`,
        audio: `They also have a Reader app that turns any document into an audiobook. PDFs, articles, research papers — listen to anything on your commute. Content creators, this is your secret weapon.`
      },
      {
        timeRange: '00:48 - 00:60',
        visual: `Pricing page showing free tier. Animated subscribe button. Text: "Link below 👇"`,
        audio: `You can start completely free today. I've dropped the link in the description. Subscribe because I'm dropping one insane AI tool every single day.`
      }
    ]
  },
  'cursor': {
    role: 'software engineers',
    task: 'coding',
    competitor: 'VS Code',
    expensive: 'senior developers',
    storyboard: (name, tagline, features, pricing) => [
      {
        timeRange: '00:00 - 00:05',
        visual: `Code editor with files flying. Bold text: "This AI writes your ENTIRE codebase"`,
        audio: `Developers, stop editing files one by one. This AI assistant writes across your entire project simultaneously.`
      },
      {
        timeRange: '00:05 - 00:18',
        visual: `Show ${name} with a prompt: "Implement dark mode across all pages". Multiple files updating at once in the sidebar.`,
        audio: `It's called ${name}. You press one shortcut, describe the feature you want, and it edits ten, twenty files at once. It reads your entire codebase, understands the architecture, and makes changes that actually work.`
      },
      {
        timeRange: '00:18 - 00:35',
        visual: `Show terminal running commands automatically. Git diff showing additions and deletions. Click "Apply All".`,
        audio: `It runs terminal commands, installs packages, and shows you the full Git diff before applying anything. It's like pair programming with a senior engineer who never sleeps and never complains.`
      },
      {
        timeRange: '00:35 - 00:48',
        visual: `Time-lapse: entire MVP being built. File count going up. Text: "Full app in 2 hours"`,
        audio: `I built a complete MVP in two hours using ${name}. Authentication, database, API routes, frontend — all from chat prompts. This is the future of software engineering.`
      },
      {
        timeRange: '00:48 - 00:60',
        visual: `Download page. Free trial highlighted. Animated arrow down. Text: "FREE trial 👇"`,
        audio: `It has a free trial and it'll blow your mind. Link in the description. Hit subscribe — I'm revealing one killer dev tool every single day.`
      }
    ]
  },
  'julius ai': {
    role: 'data analysts',
    task: 'data analysis',
    competitor: 'Excel',
    expensive: 'data consultants',
    storyboard: (name, tagline, features, pricing) => [
      {
        timeRange: '00:00 - 00:05',
        visual: `Spreadsheet exploding into charts. Bold text: "This AI replaces your DATA ANALYST"`,
        audio: `Stop paying data analysts. This free AI tool analyzes your entire spreadsheet in ten seconds.`
      },
      {
        timeRange: '00:05 - 00:18',
        visual: `Upload CSV to ${name}. Type: "Show me monthly revenue trends with predictions". Charts generating instantly.`,
        audio: `It's called ${name}. Upload any CSV, Excel file, or PDF — ask it anything in plain English — and it generates professional charts, regressions, and predictions instantly.`
      },
      {
        timeRange: '00:18 - 00:35',
        visual: `Show multiple chart types being generated: bar charts, scatter plots, forecasting lines. Python code visible underneath.`,
        audio: `It writes Python code under the hood, creates publication-ready visualizations, and even does predictive analytics. Business owners, researchers, students — this replaces tools that cost hundreds per month.`
      },
      {
        timeRange: '00:35 - 00:48',
        visual: `Show asking a follow-up question: "Which product has the highest margin?" — AI responds with answer and chart.`,
        audio: `And you can just keep asking follow-up questions like you're chatting with a data scientist. No formulas. No pivot tables. Just answers.`
      },
      {
        timeRange: '00:48 - 00:60',
        visual: `Free tier pricing. Arrow pointing down. Text: "Try FREE — Link below 👇"`,
        audio: `Free to start. Link in the description. Comment what data you'd analyze with this — and subscribe for daily AI tool discoveries.`
      }
    ]
  },
  'notebooklm': {
    role: 'researchers',
    task: 'research',
    competitor: 'ChatGPT',
    expensive: 'research assistants',
    storyboard: (name, tagline, features, pricing) => [
      {
        timeRange: '00:00 - 00:05',
        visual: `Stack of documents transforming into a podcast. Bold text: "Google's SECRET AI tool"`,
        audio: `Google built an AI tool that turns any document into a full podcast conversation. And it's completely free.`
      },
      {
        timeRange: '00:05 - 00:18',
        visual: `Upload PDFs and slides to ${name}. AI generating a summary. Show source citations with page numbers.`,
        audio: `It's called ${name}. Upload your research papers, textbooks, or slides — and it becomes an AI expert on YOUR documents. It answers questions and cites the exact page numbers.`
      },
      {
        timeRange: '00:18 - 00:35',
        visual: `Show the Audio Overview feature. Two AI voices having a natural conversation about the uploaded content.`,
        audio: `But the killer feature is Audio Overview. It generates a natural two-person podcast discussion about your documents. Two AI hosts debating, explaining, and breaking down complex topics. Students, this is a game-changer for exam prep.`
      },
      {
        timeRange: '00:35 - 00:48',
        visual: `Show asking deep questions about the document. AI responding with cited answers. Highlight "no hallucination" badge.`,
        audio: `Unlike ChatGPT, it only uses YOUR uploaded sources. No hallucinations. No made-up facts. Every answer is grounded in your actual documents with citations.`
      },
      {
        timeRange: '00:48 - 00:60',
        visual: `Google logo. "100% FREE" text. Arrow pointing down.`,
        audio: `It's made by Google and it's one hundred percent free. Link in the description. Subscribe — I'm dropping one insane AI tool every single day.`
      }
    ]
  }
};

// Default config for tools not in the list
const DEFAULT_CONFIG = {
  role: 'professionals',
  task: 'repetitive work',
  competitor: 'manual methods',
  expensive: 'agencies',
};

export function generateShortsScript(product) {
  const name = product.name;
  const tagline = product.tagline;
  const category = product.category;
  const features = product.features;
  const pricing = product.pricing;
  const audience = product.targetAudience;
  const affiliate = product.affiliateLink;

  // Find tool-specific config
  const configKey = Object.keys(TOOL_CONFIGS).find(k => name.toLowerCase().includes(k));
  const config = configKey ? TOOL_CONFIGS[configKey] : DEFAULT_CONFIG;

  const vars = {
    NAME: name,
    ROLE: config.role,
    TASK: config.task,
    COMPETITOR: config.competitor,
    EXPENSIVE: config.expensive,
    PRICE: 'FREE',
    NUMBER: String(Math.floor(Math.random() * 5 + 2)),
  };

  // Generate storyboard
  const sections = config.storyboard
    ? config.storyboard(name, tagline, features, pricing)
    : [
        { timeRange: '00:00 - 00:05', visual: `Bold text zoom onto ${name}`, audio: fillTemplate(pickRandom(HOOK_TEMPLATES), vars) },
        { timeRange: '00:05 - 00:18', visual: `Show ${name} interface demo`, audio: `It's called ${name}, the ${tagline}. Just describe what you want and the AI does the rest in seconds.` },
        { timeRange: '00:18 - 00:35', visual: `Feature showcase: ${features[0]}, ${features[1]}`, audio: `It handles ${features[0].toLowerCase()} and ${features[1].toLowerCase()}. Whether you're a beginner or a pro, this saves hours of work.` },
        { timeRange: '00:35 - 00:48', visual: `Show more features and use cases`, audio: `If you're a ${audience.split(',')[0].trim().toLowerCase()}, you need to add this to your workflow today.` },
        { timeRange: '00:48 - 00:60', visual: `Pricing + CTA arrow pointing down`, audio: `${pricing} Link in the description. Subscribe for daily AI tool reviews!` }
      ];

  // Generate 4 viral titles
  const shuffledTitles = [...TITLE_TEMPLATES].sort(() => Math.random() - 0.5);
  const titles = shuffledTitles.slice(0, 4).map(t => fillTemplate(t, vars));

  // Tags with #Shorts and trending hashtags
  const tags = [
    'Shorts', 'AITools', 'AI', 'TechReview',
    name.replace(/\s+/g, ''), category.replace(/\s+/g, ''),
    'Productivity', 'FreeAI', 'ArtificialIntelligence',
    'TechTok', 'SaaS', 'Coding', 'Automation'
  ];

  // SEO-optimized description with hashtags
  const hashtagBlock = tags.slice(0, 8).map(t => `#${t}`).join(' ');
  const description = `${fillTemplate(pickRandom(HOOK_TEMPLATES), vars)}

🔗 Try ${name} FREE: ${affiliate}

${name} is the ${tagline}. In this Short, I show you exactly how it works and why ${config.role} are switching to it.

✅ What ${name} does:
${features.map(f => `• ${f}`).join('\n')}

💰 Pricing: ${pricing}

👉 Subscribe for daily AI tool reviews!
👇 Drop a comment: would you use this?

${hashtagBlock}`;

  return {
    productName: name,
    category,
    titles,
    description,
    tags,
    storyboard: sections
  };
}

export function formatScriptToMarkdown(scriptData) {
  let md = `# YouTube Shorts Script & Storyboard: ${scriptData.productName}\n\n`;
  
  md += `## 💡 Proposed Metadata\n`;
  md += `### Suggested Titles (Hook-Optimized):\n`;
  scriptData.titles.forEach((t, i) => {
    md += `${i + 1}. **${t}**\n`;
  });
  md += `\n`;
  md += `### Tags:\n\`${scriptData.tags.join(', ')}\`\n\n`;
  
  md += `### Video Description:\n`;
  md += `\`\`\`text\n${scriptData.description}\n\`\`\`\n\n`;
  
  md += `## 🎬 Visual Storyboard & Audio Script (60s Limit)\n`;
  md += `| Time | 🎥 Visual Cues | 🎙️ Narration |\n`;
  md += `| :--- | :--- | :--- |\n`;
  
  scriptData.storyboard.forEach(s => {
    md += `| **${s.timeRange}** | ${s.visual} | *"${s.audio}"* |\n`;
  });
  
  md += `\n---\n*Generated by YouTube SaaS Reviewer v2.0 — Hook-First Engine*`;

  return md;
}
